### ISSUE TITLE
Webrtcsink Renegotiation of caps

### ISSUE THREAD

**Issue by massis08** [centricular/webrtcsink#54]
Hello, me and my colleague @leaonidas are using the webrtcsink plugin in a project, and we and have a few questions.

We are receiving a h265 stream with an udpsrc, then decoding it and sending it to the webrtcsink. If we stop sending the h265 stream and start sending another h265 stream, it will trigger the an event to renegotiate the caps, and apparently the webrtcsink does not support that.

![unknown](https://user-images.githubusercontent.com/66794355/165802668-06fcdded-522f-430f-895a-eef11354a955.png)

Is there any way to work around this or are you expecting to add caps renegotiation to the plugin?

We would also like to know if it is possible to use webrtcsink when we only have an audio consumer.

Many thanks!

**Comment by MathieuDuponchelle** [comment]
Closing this, please reopen if you need to discuss more.

**Comment by leaonidas** [comment]
Hello,

I tried your suggestion of adding the videoconvert, capsfilter and the videoscale, but because the video format differs the caps are no longer strictly equal. So in the plugin code, I added the default negotiation event if the caps are not strictly equal and it seemed to fix the problem.

![Screenshot from 2022-05-09 09-45-53](https://user-images.githubusercontent.com/41586760/167374861-8d2758d7-ec45-41ba-8bef-f470a30b9b66.png)

I don't know if this is a feasible solution, as I don't know the implication of this caps negotiation in the SDP one. But for very similar caps it works.

**Comment by MathieuDuponchelle** [comment]
Hello @leaonidas , the idea with the capsfilter is that once it has seen caps a first time, you then want to constrain future caps accordingly. If you do that, then the format field at least should not change (as videoconvert will take care of converting to the initial format). The issue with actual SDP renegotiation is that (mostly in the case of H264), providing the encoder with a different raw format may cause it to output a different `profile-level-id` to the one that was initially added to the SDP, thus potentially breaking clients if they don't support the new format.

In practice here I think we could relax the check to allow for your use case, and simply log a warning and let the event through as you did, and hope for the best :)
